# This is a basic workflow to help you get started with Actions

name: CI_Hello_simple

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      # Runs a single command using the runners shell
      - name: Diga oi
        run: echo "Hello, world!"

      # Runs a set of commands using the runners shell
      - name: Diga valeu
        run: echo "Valeu -bye!"
        
